server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_system
    username: postgres
    password: pass1234
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 45831608789-7bda4ggcovrm54k2hmf4l7leulhuuonh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
        http: debug
      hibernate: debug

