services:
  order-system-backend:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - FRONTEND_ROOT_URL=${FRONTEND_ROOT_URL}
      - JWT_KEY=${JWT_KEY}
    networks:
      - nginx_proxied
      - order-system
    restart: unless-stopped

networks:
  nginx_proxied:
    external: true
  order-system:
    external: true
