services:
  order-system-backend:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - FRONTEND_ROOT_URL=${FRONTEND_ROOT_URL}
      - JWT_KEY=1b7c413735bfa514c7c2fea3faaab5a1d7e368b0396af31fe9dbc4e0538e4d49
      - MY_COOL_VAR=my-cool-var-yay
    networks:
      - nginx_proxied
      - order-system
    restart: unless-stopped

networks:
  nginx_proxied:
    external: true
  order-system:
    external: true
